### ISSUE TITLE
Bug: Square Switch

### ISSUE THREAD

**Issue by marcobiedermann** [eliorshalev/tootik#2]
I've noticed that the square switch on https://eliorshalev.github.io/tootik/ does not work.
You have to convert the id to lowercase:
`id="Square"` -> `id="square"`

![image](https://cloud.githubusercontent.com/assets/5244986/16458414/446f0552-3e1f-11e6-9055-cf88a90b8a16.png)

I would send you a pull request but the code is minified and you probably got the source code locally :)

**Comment by eliorshalev** [comment]
Hi @marcobiedermann, Thank you for your time and comment!
Actually I already fixed this issue.. 👍
